# Site settings
title: Smart Buffalo
email: smartbuffalocollaborative@gmail.com
description: We are a local brigade of Code for America committed to making government work better in Buffalo.
url: "https://smartbuffalo.github.io/"
twitter_username: smart_buffalo
github_username:  opensavannah
paginate: 5
paginate_path: "blog/page:num/"

# Build settings
markdown: kramdown
