# Site settings
title: Code for Buffalo
email: leadership@codeforbuffalo.org
description: Buffalo's Code for America Brigade using data and technology for the public good.
url: "https://codeforbuffalo.org/"
twitter_username: codeforbuffalo
github_username:  codeforbuffalo
image: "images/ChangeOnlyHappens.png"
paginate: 5
paginate_path: "blog/page:num/"

# Build settings
markdown: kramdown

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
