# Site settings
title: Code for Buffalo
email: info@codeforbuffalo.org
description: We are a local brigade of Code for America committed to using data and technology for the public good in Buffalo.
url: "https://codeforbuffalo.github.io/"
twitter_username: codeforbuffalo
github_username:  codeforbuffalo
paginate: 5
paginate_path: "blog/page:num/"

# Build settings
markdown: kramdown
